// Optional "Interview prep" box: 5 classic quick interview questions per day (Python unless stated).
// Not required for unlocking. None of these repeat a problem from the LeetCode DSA or DB containers.
window.INTERVIEW_PREP = {
  1: ["Reverse a list without using reverse() or slicing.",
      "Find the second largest number in a list in a single pass.",
      "Remove duplicates from a list while keeping the original order.",
      "Find the maximum and minimum of a list without max() or min().",
      "Rotate a list to the right by k positions."],
  2: ["Reverse a string without slicing.",
      "Check if a string is a palindrome, ignoring case and spaces.",
      "Count the vowels in a string.",
      "Reverse the order of words in a sentence.",
      "Capitalize the first letter of every word without using .title()."],
  3: ["Check if a number is prime.",
      "Print the first n Fibonacci numbers, iteratively.",
      "Compute the factorial of n, recursively and iteratively.",
      "Check if a number is an Armstrong number.",
      "Find the sum of the digits of an integer."],
  4: ["Count the frequency of each character in a string using a dict.",
      "Find the first non-repeating character in a string.",
      "Find the most frequent element in a list.",
      "Merge two dicts; when a key is in both, add the values.",
      "Invert a dict so the values become keys."],
  5: ["Flatten a nested list of any depth.",
      "Find the missing number in a list containing 1..n with one number missing.",
      "Move all zeros to the end of a list, keeping the order of the other elements.",
      "Find the common elements of two lists.",
      "Split a list into chunks of size n."],
  6: ["Check if one string is a rotation of another.",
      "Remove duplicate characters from a string, keeping the first occurrence.",
      "Find the longest word in a sentence.",
      "Compress a string: \"aaabbc\" → \"a3b2c1\".",
      "Check if a string contains only digits without using isdigit()."],
  7: ["Swap two variables without a temporary variable.",
      "Check if a year is a leap year.",
      "Find the GCD and LCM of two numbers.",
      "Convert a decimal number to binary without bin().",
      "Check if a number is a perfect number."],
  8: ["Implement bubble sort.",
      "Implement insertion sort.",
      "Implement selection sort.",
      "Merge two sorted lists into one sorted list without sort().",
      "Find the kth smallest element of a list without sorting the whole list."],
  9: ["Compute x to the power n recursively.",
      "Sum a list recursively.",
      "Reverse a string recursively.",
      "Tower of Hanoi: print the moves for n disks.",
      "Count the digits of a number recursively."],
  10: ["Sort a list of dicts by a given key.",
       "Sort a list of tuples by their second element.",
       "Return all pairs in a list whose sum equals a target.",
       "Turn two lists (keys, values) into a dict with zip().",
       "Use a list comprehension to get the squares of the even numbers from 1 to 20."],
  11: ["Transpose a matrix.",
       "Add two matrices.",
       "Multiply two matrices.",
       "Find the sum of both diagonals of a square matrix.",
       "Check if a matrix is symmetric."],
  12: ["Print all substrings of a string.",
       "Check if a string is a pangram.",
       "Count how many times a word appears in a paragraph, case-insensitive.",
       "Convert \"hello world\" to camelCase and to snake_case.",
       "Remove all punctuation from a string."],
  13: ["Find the intersection and union of two lists without using sets.",
       "Find the duplicates in a list and how many times each appears.",
       "Check whether one list is a subset of another.",
       "Find the largest difference between two elements where the larger one comes later.",
       "Find the indices of all occurrences of an element in a list."],
  14: ["Check if a number is a palindrome without converting it to a string.",
       "Print all primes up to n using the Sieve of Eratosthenes.",
       "Find the prime factors of a number.",
       "Check if a number is a strong number (sum of the factorials of its digits equals the number).",
       "Convert a Roman numeral to an integer."],
  15: ["Write a Stack class with push, pop, peek and is_empty.",
       "Write a Queue class using two stacks.",
       "Write a Rectangle class with area(), perimeter() and __str__.",
       "Write a BankAccount class that refuses withdrawals larger than the balance.",
       "Write a class that counts how many instances of it have been created."],
  16: ["Write a decorator that prints how long a function takes to run.",
       "Write a generator that yields Fibonacci numbers forever.",
       "Write a context manager that prints \"enter\" and \"exit\", as a class and with @contextmanager.",
       "Write a function that accepts any positional and keyword arguments and prints them.",
       "Show the difference between a shallow copy and a deep copy with a nested list."],
  17: ["Implement a singly linked list with append, prepend and delete-by-value.",
       "Find the middle node of a linked list in one pass.",
       "Count the nodes of a linked list recursively.",
       "Remove duplicates from a sorted linked list.",
       "Convert a linked list to a Python list and back."],
  18: ["Find the longest common prefix of a list of strings.",
       "Check if a string is an isogram (no letter repeats).",
       "Find the most frequent character in a string; on a tie, return the one that appears first.",
       "Replace every space in a string with \"%20\" without using replace().",
       "Count the uppercase letters, lowercase letters, digits and special characters in a string."],
  19: ["Group a list of words into a dict by their first letter.",
       "Count the words in a text and print the 3 most common.",
       "Flatten a nested dict: {\"a\": {\"b\": 1}} → {\"a.b\": 1}.",
       "Parse a JSON string and print it pretty, sorted by keys.",
       "Given (user, amount) transactions, return the total amount per user."],
  20: ["Find the pair of elements with the smallest absolute difference.",
       "Find the leaders in a list (elements greater than everything to their right).",
       "Rearrange a list so positive and negative numbers alternate.",
       "Find the equilibrium index, where the sum on the left equals the sum on the right.",
       "Count the pairs in a list whose difference is k."],
  21: ["Why is def f(x=[]) dangerous? Show the bug and the fix.",
       "What's the difference between is and ==? Give an example where they differ.",
       "What does [[0] * 3] * 3 create, and why is it a bug?",
       "Explain *args and **kwargs with an example call.",
       "List, tuple, set, dict: when would you use each?"],
  22: ["Print all binary strings of length n.",
       "Compute nCr recursively.",
       "Check if a string is a palindrome recursively.",
       "Keep summing the digits of a number until one digit is left.",
       "Print the numbers from 1 to n without a loop."],
  23: ["Read a file and count its lines, words and characters.",
       "Read a CSV file and compute the average of one column.",
       "Find the 10 most frequent IP addresses in a web server log file.",
       "Write a list of dicts to a CSV file with a header row.",
       "Read a large file line by line and yield only the lines containing \"ERROR\"."],
  24: ["SQL: find employees who joined in the last 30 days.",
       "SQL: count orders per customer, showing only customers with more than 3 orders.",
       "SQL: get the top 3 products by total sales.",
       "SQL: find the total revenue per month.",
       "SQL: find employees earning more than their department's average salary."],
  25: ["Implement a min-heap with push and pop without heapq.",
       "Implement a hash map with put, get and remove using lists (chaining).",
       "Implement a fixed-size circular queue.",
       "Implement a deque (append, appendleft, pop, popleft) with a doubly linked list.",
       "Implement a binary search tree with insert and in-order traversal."],
  26: ["Check if a string is a valid IPv4 address.",
       "Validate an email address with a regex.",
       "Convert a number from 0 to 999 into words (342 → \"three hundred forty two\").",
       "Find the first repeated word in a sentence.",
       "Run-length decoding: \"a3b2\" → \"aaabb\"."],
  27: ["Check if a number is a power of two without a loop.",
       "Find the integer square root of a number without math.sqrt().",
       "Generate Pascal's triangle up to n rows.",
       "Print all Armstrong numbers between 1 and 1000.",
       "Convert a list of Celsius values to Fahrenheit with map() and a lambda."],
  28: ["What's the difference between a process and a thread in Python?",
       "What is the GIL, and when does it matter?",
       "What's the difference between PUT and PATCH?",
       "What happens, step by step, when you type a URL into a browser?",
       "SQL vs NoSQL: when would you choose each?"],
  29: ["Find the majority element (appears more than n/2 times).",
       "Find the length of the longest run of equal consecutive numbers.",
       "Find the smallest positive integer missing from an unsorted list.",
       "Check if a list is sorted.",
       "Find the second smallest element without sorting."],
  30: ["FizzBuzz from 1 to 100.",
       "Count the words in a string without split().",
       "Find the sum of the even Fibonacci numbers below 4 million.",
       "Join a list of strings with commas without join().",
       "Print a pyramid of stars of height n."],
};
