// Extra practice problems on real platforms, per plan day (1–30).
// Every link and title was checked against the platform (LeetCode, HackerRank,
// PGExercises, Exercism, Use The Index Luke). cat = Python / SQL / DSA.
window.PRACTICE = {
  1: [
    {"cat": "Python", "src": "HackerRank", "t": "Lists", "u": "https://www.hackerrank.com/challenges/python-lists/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Tuples ", "u": "https://www.hackerrank.com/challenges/python-tuples/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "Revising the Select Query I", "u": "https://www.hackerrank.com/challenges/revising-the-select-query/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Control which rows are retrieved", "u": "https://pgexercises.com/questions/basic/where.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Running Sum of 1d Array", "u": "https://leetcode.com/problems/running-sum-of-1d-array/", "n": "1480", "d": "Easy"},
  ],
  2: [
    {"cat": "Python", "src": "HackerRank", "t": "Introduction to Sets", "u": "https://www.hackerrank.com/challenges/py-introduction-to-sets/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "collections.Counter()", "u": "https://www.hackerrank.com/challenges/collections-counter/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Retrieve the start times of members' bookings", "u": "https://pgexercises.com/questions/joins/simplejoin.html"},
    {"cat": "SQL", "src": "HackerRank", "t": "Population Census ", "u": "https://www.hackerrank.com/challenges/asian-population/problem", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Number of Good Pairs", "u": "https://leetcode.com/problems/number-of-good-pairs/", "n": "1512", "d": "Easy"},
  ],
  3: [
    {"cat": "Python", "src": "HackerRank", "t": "Find the Runner-Up Score!  ", "u": "https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Nested Lists", "u": "https://www.hackerrank.com/challenges/nested-list/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "Weather Observation Station 3", "u": "https://www.hackerrank.com/challenges/weather-observation-station-3/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Working with dates", "u": "https://pgexercises.com/questions/basic/date.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Merge Sorted Array", "u": "https://leetcode.com/problems/merge-sorted-array/", "n": "88", "d": "Easy"},
  ],
  4: [
    {"cat": "Python", "src": "HackerRank", "t": "Finding the percentage", "u": "https://www.hackerrank.com/challenges/finding-the-percentage/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Word Order", "u": "https://www.hackerrank.com/challenges/word-order/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Revising Aggregations - The Count Function", "u": "https://www.hackerrank.com/challenges/revising-aggregations-the-count-function/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Count the number of recommendations each member makes.", "u": "https://pgexercises.com/questions/aggregates/count3.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Majority Element", "u": "https://leetcode.com/problems/majority-element/", "n": "169", "d": "Easy"},
  ],
  5: [
    {"cat": "Python", "src": "HackerRank", "t": "List Comprehensions", "u": "https://www.hackerrank.com/challenges/list-comprehensions/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Zipped!", "u": "https://www.hackerrank.com/challenges/zipped/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Insert some data into a table", "u": "https://pgexercises.com/questions/updates/insert.html"},
    {"cat": "SQL", "src": "PGExercises", "t": "Update multiple rows and columns at the same time", "u": "https://pgexercises.com/questions/updates/updatemultiple.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Reverse String", "u": "https://leetcode.com/problems/reverse-string/", "n": "344", "d": "Easy"},
  ],
  6: [
    {"cat": "Python", "src": "HackerRank", "t": "Iterables and Iterators", "u": "https://www.hackerrank.com/challenges/iterables-and-iterators/problem", "d": "Medium"},
    {"cat": "Python", "src": "HackerRank", "t": "itertools.combinations()", "u": "https://www.hackerrank.com/challenges/itertools-combinations/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Produce a list of all members, along with their recommender", "u": "https://pgexercises.com/questions/joins/self2.html"},
    {"cat": "SQL", "src": "PGExercises", "t": "Produce a list of all members who have used a tennis court", "u": "https://pgexercises.com/questions/joins/threejoin.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Squares of a Sorted Array", "u": "https://leetcode.com/problems/squares-of-a-sorted-array/", "n": "977", "d": "Easy"},
  ],
  7: [
    {"cat": "Python", "src": "HackerRank", "t": "Standardize Mobile Number Using Decorators", "u": "https://www.hackerrank.com/challenges/standardize-mobile-number-using-decorators/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Decorators 2 - Name Directory", "u": "https://www.hackerrank.com/challenges/decorators-2-name-directory/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "Average Population of Each Continent", "u": "https://www.hackerrank.com/challenges/average-population-of-each-continent/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "List the total slots booked per facility", "u": "https://pgexercises.com/questions/aggregates/fachours.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Maximum Average Subarray I", "u": "https://leetcode.com/problems/maximum-average-subarray-i/", "n": "643", "d": "Easy"},
  ],
  8: [
    {"cat": "Python", "src": "HackerRank", "t": "Classes: Dealing with Complex Numbers", "u": "https://www.hackerrank.com/challenges/class-1-dealing-with-complex-numbers/problem", "d": "Medium"},
    {"cat": "Python", "src": "Exercism", "t": "Bank Account", "u": "https://exercism.org/tracks/python/exercises/bank-account"},
    {"cat": "SQL", "src": "HackerRank", "t": "Type of Triangle", "u": "https://www.hackerrank.com/challenges/what-type-of-triangle/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Classify results into buckets", "u": "https://pgexercises.com/questions/basic/classify.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Find Pivot Index", "u": "https://leetcode.com/problems/find-pivot-index/", "n": "724", "d": "Easy"},
  ],
  9: [
    {"cat": "Python", "src": "HackerRank", "t": "Check Subset", "u": "https://www.hackerrank.com/challenges/py-check-subset/problem", "d": "Easy"},
    {"cat": "Python", "src": "Exercism", "t": "Robot Name", "u": "https://exercism.org/tracks/python/exercises/robot-name"},
    {"cat": "SQL", "src": "PGExercises", "t": "Produce a list of all members, along with their recommender, using no joins.", "u": "https://pgexercises.com/questions/joins/sub.html"},
    {"cat": "SQL", "src": "LeetCode", "t": "Customers Who Never Order", "u": "https://leetcode.com/problems/customers-who-never-order/", "n": "183", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Baseball Game", "u": "https://leetcode.com/problems/baseball-game/", "n": "682", "d": "Easy"},
  ],
  10: [
    {"cat": "Python", "src": "HackerRank", "t": "Merge the Tools!", "u": "https://www.hackerrank.com/challenges/merge-the-tools/problem", "d": "Medium"},
    {"cat": "Python", "src": "HackerRank", "t": "Compress the String! ", "u": "https://www.hackerrank.com/challenges/compress-the-string/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "The Report", "u": "https://www.hackerrank.com/challenges/the-report/problem", "d": "Medium"},
    {"cat": "SQL", "src": "LeetCode", "t": "Department Highest Salary", "u": "https://leetcode.com/problems/department-highest-salary/", "n": "184", "d": "Medium"},
    {"cat": "DSA", "src": "LeetCode", "t": "Remove All Adjacent Duplicates In String", "u": "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/", "n": "1047", "d": "Easy"},
  ],
  11: [
    {"cat": "Python", "src": "Exercism", "t": "Clock", "u": "https://exercism.org/tracks/python/exercises/clock"},
    {"cat": "Python", "src": "Exercism", "t": "Custom Set", "u": "https://exercism.org/tracks/python/exercises/custom-set"},
    {"cat": "SQL", "src": "PGExercises", "t": "Find the upward recommendation chain for member ID 27", "u": "https://pgexercises.com/questions/recursive/getupward.html"},
    {"cat": "SQL", "src": "PGExercises", "t": "Find the downward recommendation chain for member ID 1", "u": "https://pgexercises.com/questions/recursive/getdownward.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Car Fleet", "u": "https://leetcode.com/problems/car-fleet/", "n": "853", "d": "Medium"},
  ],
  12: [
    {"cat": "Python", "src": "HackerRank", "t": "Exceptions", "u": "https://www.hackerrank.com/challenges/exceptions/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Incorrect Regex", "u": "https://www.hackerrank.com/challenges/incorrect-regex/problem", "d": "Easy"},
    {"cat": "SQL", "src": "LeetCode", "t": "Rank Scores", "u": "https://leetcode.com/problems/rank-scores/", "n": "178", "d": "Medium"},
    {"cat": "SQL", "src": "PGExercises", "t": "Rank members by (rounded) hours used", "u": "https://pgexercises.com/questions/aggregates/rankmembers.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "First Bad Version", "u": "https://leetcode.com/problems/first-bad-version/", "n": "278", "d": "Easy"},
  ],
  13: [
    {"cat": "Python", "src": "HackerRank", "t": "Collections.deque()", "u": "https://www.hackerrank.com/challenges/py-collections-deque/problem", "d": "Easy"},
    {"cat": "Python", "src": "Exercism", "t": "Circular Buffer", "u": "https://exercism.org/tracks/python/exercises/circular-buffer"},
    {"cat": "SQL", "src": "PGExercises", "t": "Calculate a rolling average of total revenue", "u": "https://pgexercises.com/questions/aggregates/rollingavg.html"},
    {"cat": "SQL", "src": "LeetCode", "t": "Human Traffic of Stadium", "u": "https://leetcode.com/problems/human-traffic-of-stadium/", "n": "601", "d": "Hard"},
    {"cat": "DSA", "src": "LeetCode", "t": "Capacity To Ship Packages Within D Days", "u": "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/", "n": "1011", "d": "Medium"},
  ],
  14: [
    {"cat": "Python", "src": "Exercism", "t": "Simple Linked List", "u": "https://exercism.org/tracks/python/exercises/simple-linked-list"},
    {"cat": "Python", "src": "Exercism", "t": "Linked List", "u": "https://exercism.org/tracks/python/exercises/linked-list"},
    {"cat": "SQL", "src": "HackerRank", "t": "New Companies", "u": "https://www.hackerrank.com/challenges/the-company/problem", "d": "Medium"},
    {"cat": "SQL", "src": "LeetCode", "t": "Employees Earning More Than Their Managers", "u": "https://leetcode.com/problems/employees-earning-more-than-their-managers/", "n": "181", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Remove Duplicates from Sorted List", "u": "https://leetcode.com/problems/remove-duplicates-from-sorted-list/", "n": "83", "d": "Easy"},
  ],
  15: [
    {"cat": "Python", "src": "HackerRank", "t": "ginortS", "u": "https://www.hackerrank.com/challenges/ginorts/problem", "d": "Medium"},
    {"cat": "Python", "src": "HackerRank", "t": "Athlete Sort", "u": "https://www.hackerrank.com/challenges/python-sort-sort/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Placements", "u": "https://www.hackerrank.com/challenges/placements/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Symmetric Pairs", "u": "https://www.hackerrank.com/challenges/symmetric-pairs/problem", "d": "Medium"},
    {"cat": "DSA", "src": "LeetCode", "t": "Find the Duplicate Number", "u": "https://leetcode.com/problems/find-the-duplicate-number/", "n": "287", "d": "Medium"},
  ],
  16: [
    {"cat": "Python", "src": "HackerRank", "t": "sWAP cASE", "u": "https://www.hackerrank.com/challenges/swap-case/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "String Split and Join", "u": "https://www.hackerrank.com/challenges/python-string-split-and-join/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "Weather Observation Station 6", "u": "https://www.hackerrank.com/challenges/weather-observation-station-6/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Find telephone numbers with parentheses", "u": "https://pgexercises.com/questions/string/reg.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Copy List with Random Pointer", "u": "https://leetcode.com/problems/copy-list-with-random-pointer/", "n": "138", "d": "Medium"},
  ],
  17: [
    {"cat": "Python", "src": "HackerRank", "t": "Alphabet Rangoli", "u": "https://www.hackerrank.com/challenges/alphabet-rangoli/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Designer Door Mat", "u": "https://www.hackerrank.com/challenges/designer-door-mat/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "Occupations", "u": "https://www.hackerrank.com/challenges/occupations/problem", "d": "Medium"},
    {"cat": "SQL", "src": "LeetCode", "t": "Nth Highest Salary", "u": "https://leetcode.com/problems/nth-highest-salary/", "n": "177", "d": "Medium"},
    {"cat": "DSA", "src": "LeetCode", "t": "Palindrome Linked List", "u": "https://leetcode.com/problems/palindrome-linked-list/", "n": "234", "d": "Easy"},
  ],
  18: [
    {"cat": "Python", "src": "Exercism", "t": "Grade School", "u": "https://exercism.org/tracks/python/exercises/grade-school"},
    {"cat": "Python", "src": "HackerRank", "t": "Company Logo", "u": "https://www.hackerrank.com/challenges/most-commons/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Top Competitors", "u": "https://www.hackerrank.com/challenges/full-score/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Ollivander's Inventory", "u": "https://www.hackerrank.com/challenges/harry-potter-and-wands/problem", "d": "Medium"},
    {"cat": "DSA", "src": "LeetCode", "t": "Symmetric Tree", "u": "https://leetcode.com/problems/symmetric-tree/", "n": "101", "d": "Easy"},
  ],
  19: [
    {"cat": "Python", "src": "HackerRank", "t": "DefaultDict Tutorial", "u": "https://www.hackerrank.com/challenges/defaultdict-tutorial/problem", "d": "Easy"},
    {"cat": "Python", "src": "HackerRank", "t": "Collections.OrderedDict()", "u": "https://www.hackerrank.com/challenges/py-collections-ordereddict/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "SQL Project Planning", "u": "https://www.hackerrank.com/challenges/sql-projects/problem", "d": "Medium"},
    {"cat": "SQL", "src": "PGExercises", "t": "List the total slots booked per facility in a given month", "u": "https://pgexercises.com/questions/aggregates/fachoursbymonth.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Path Sum", "u": "https://leetcode.com/problems/path-sum/", "n": "112", "d": "Easy"},
  ],
  20: [
    {"cat": "Python", "src": "Exercism", "t": "Binary Search", "u": "https://exercism.org/tracks/python/exercises/binary-search"},
    {"cat": "Python", "src": "HackerRank", "t": "Collections.namedtuple()", "u": "https://www.hackerrank.com/challenges/py-collections-namedtuple/problem", "d": "Easy"},
    {"cat": "SQL", "src": "Use The Index, Luke", "t": "3-Minute Quiz: What do you know about SQL performance?", "u": "https://use-the-index-luke.com/3-minute-test"},
    {"cat": "SQL", "src": "PGExercises", "t": "List each member's first booking after September 1st 2012", "u": "https://pgexercises.com/questions/aggregates/nbooking.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Average of Levels in Binary Tree", "u": "https://leetcode.com/problems/average-of-levels-in-binary-tree/", "n": "637", "d": "Easy"},
  ],
  21: [
    {"cat": "Python", "src": "HackerRank", "t": "Validating Email Addresses With a Filter ", "u": "https://www.hackerrank.com/challenges/validate-list-of-email-address-with-filter/problem", "d": "Medium"},
    {"cat": "Python", "src": "HackerRank", "t": "Reduce Function", "u": "https://www.hackerrank.com/challenges/reduce-function/problem", "d": "Medium"},
    {"cat": "SQL", "src": "PGExercises", "t": "Find the total revenue of each facility", "u": "https://pgexercises.com/questions/aggregates/facrev.html"},
    {"cat": "SQL", "src": "PGExercises", "t": "Find facilities with a total revenue less than 1000", "u": "https://pgexercises.com/questions/aggregates/facrev2.html"},
    {"cat": "DSA", "src": "LeetCode", "t": "Search in a Binary Search Tree", "u": "https://leetcode.com/problems/search-in-a-binary-search-tree/", "n": "700", "d": "Easy"},
  ],
  22: [
    {"cat": "Python", "src": "Exercism", "t": "Sublist", "u": "https://exercism.org/tracks/python/exercises/sublist"},
    {"cat": "Python", "src": "HackerRank", "t": "Map and Lambda Function", "u": "https://www.hackerrank.com/challenges/map-and-lambda-expression/problem", "d": "Easy"},
    {"cat": "SQL", "src": "PGExercises", "t": "Update a row based on the contents of another row", "u": "https://pgexercises.com/questions/updates/updatecalculated.html"},
    {"cat": "SQL", "src": "LeetCode", "t": "Swap Sex of Employees", "u": "https://leetcode.com/problems/swap-sex-of-employees/", "n": "627", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Relative Ranks", "u": "https://leetcode.com/problems/relative-ranks/", "n": "506", "d": "Easy"},
  ],
  23: [
    {"cat": "Python", "src": "Exercism", "t": "REST API", "u": "https://exercism.org/tracks/python/exercises/rest-api"},
    {"cat": "Python", "src": "HackerRank", "t": "Time Delta", "u": "https://www.hackerrank.com/challenges/python-time-delta/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Contest Leaderboard", "u": "https://www.hackerrank.com/challenges/contest-leaderboard/problem", "d": "Medium"},
    {"cat": "SQL", "src": "LeetCode", "t": "Calculate Special Bonus", "u": "https://leetcode.com/problems/calculate-special-bonus/", "n": "1873", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Design Twitter", "u": "https://leetcode.com/problems/design-twitter/", "n": "355", "d": "Medium"},
  ],
  24: [
    {"cat": "Python", "src": "HackerRank", "t": "Piling Up!", "u": "https://www.hackerrank.com/challenges/piling-up/problem", "d": "Medium"},
    {"cat": "Python", "src": "HackerRank", "t": "No Idea!", "u": "https://www.hackerrank.com/challenges/no-idea/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Binary Tree Nodes", "u": "https://www.hackerrank.com/challenges/binary-search-tree-1/problem", "d": "Medium"},
    {"cat": "SQL", "src": "HackerRank", "t": "Challenges", "u": "https://www.hackerrank.com/challenges/challenges/problem", "d": "Medium"},
    {"cat": "DSA", "src": "LeetCode", "t": "Top K Frequent Words", "u": "https://leetcode.com/problems/top-k-frequent-words/", "n": "692", "d": "Medium"},
  ],
  25: [
    {"cat": "Python", "src": "Exercism", "t": "Flatten Array", "u": "https://exercism.org/tracks/python/exercises/flatten-array"},
    {"cat": "Python", "src": "Exercism", "t": "Saddle Points", "u": "https://exercism.org/tracks/python/exercises/saddle-points"},
    {"cat": "SQL", "src": "HackerRank", "t": "African Cities", "u": "https://www.hackerrank.com/challenges/african-cities/problem", "d": "Easy"},
    {"cat": "SQL", "src": "LeetCode", "t": "Top Travellers", "u": "https://leetcode.com/problems/top-travellers/", "n": "1407", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Island Perimeter", "u": "https://leetcode.com/problems/island-perimeter/", "n": "463", "d": "Easy"},
  ],
  26: [
    {"cat": "Python", "src": "Exercism", "t": "Tree Building", "u": "https://exercism.org/tracks/python/exercises/tree-building"},
    {"cat": "Python", "src": "HackerRank", "t": "Calendar Module", "u": "https://www.hackerrank.com/challenges/calendar-module/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "The PADS", "u": "https://www.hackerrank.com/challenges/the-pads/problem", "d": "Medium"},
    {"cat": "SQL", "src": "LeetCode", "t": "Rearrange Products Table", "u": "https://leetcode.com/problems/rearrange-products-table/", "n": "1795", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Course Schedule II", "u": "https://leetcode.com/problems/course-schedule-ii/", "n": "210", "d": "Medium"},
  ],
  27: [
    {"cat": "Python", "src": "HackerRank", "t": "itertools.permutations()", "u": "https://www.hackerrank.com/challenges/itertools-permutations/problem", "d": "Easy"},
    {"cat": "Python", "src": "Exercism", "t": "All Your Base", "u": "https://exercism.org/tracks/python/exercises/all-your-base"},
    {"cat": "SQL", "src": "HackerRank", "t": "Interviews", "u": "https://www.hackerrank.com/challenges/interviews/problem", "d": "Hard"},
    {"cat": "SQL", "src": "LeetCode", "t": "Trips and Users", "u": "https://leetcode.com/problems/trips-and-users/", "n": "262", "d": "Hard"},
    {"cat": "DSA", "src": "LeetCode", "t": "Letter Combinations of a Phone Number", "u": "https://leetcode.com/problems/letter-combinations-of-a-phone-number/", "n": "17", "d": "Medium"},
  ],
  28: [
    {"cat": "Python", "src": "Exercism", "t": "Change", "u": "https://exercism.org/tracks/python/exercises/change"},
    {"cat": "Python", "src": "HackerRank", "t": "Text Wrap", "u": "https://www.hackerrank.com/challenges/text-wrap/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "15 Days of Learning SQL", "u": "https://www.hackerrank.com/challenges/15-days-of-learning-sql/problem", "d": "Hard"},
    {"cat": "SQL", "src": "LeetCode", "t": "Employees With Missing Information", "u": "https://leetcode.com/problems/employees-with-missing-information/", "n": "1965", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Fibonacci Number", "u": "https://leetcode.com/problems/fibonacci-number/", "n": "509", "d": "Easy"},
  ],
  29: [
    {"cat": "Python", "src": "Exercism", "t": "Knapsack", "u": "https://exercism.org/tracks/python/exercises/knapsack"},
    {"cat": "Python", "src": "HackerRank", "t": "Text Alignment", "u": "https://www.hackerrank.com/challenges/text-alignment/problem", "d": "Easy"},
    {"cat": "SQL", "src": "HackerRank", "t": "Print Prime Numbers", "u": "https://www.hackerrank.com/challenges/print-prime-numbers/problem", "d": "Medium"},
    {"cat": "SQL", "src": "LeetCode", "t": "Bank Account Summary II", "u": "https://leetcode.com/problems/bank-account-summary-ii/", "n": "1587", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Longest Increasing Subsequence", "u": "https://leetcode.com/problems/longest-increasing-subsequence/", "n": "300", "d": "Medium"},
  ],
  30: [
    {"cat": "Python", "src": "HackerRank", "t": "The Minion Game", "u": "https://www.hackerrank.com/challenges/the-minion-game/problem", "d": "Medium"},
    {"cat": "Python", "src": "HackerRank", "t": "Capitalize!", "u": "https://www.hackerrank.com/challenges/capitalize/problem", "d": "Easy"},
    {"cat": "SQL", "src": "LeetCode", "t": "Combine Two Tables", "u": "https://leetcode.com/problems/combine-two-tables/", "n": "175", "d": "Easy"},
    {"cat": "SQL", "src": "LeetCode", "t": "Duplicate Emails", "u": "https://leetcode.com/problems/duplicate-emails/", "n": "182", "d": "Easy"},
    {"cat": "DSA", "src": "LeetCode", "t": "Non-overlapping Intervals", "u": "https://leetcode.com/problems/non-overlapping-intervals/", "n": "435", "d": "Medium"},
  ],
};
