// YouTube videos used by the plan, keyed by the lookup phrase in plan.js.
// Each was checked against YouTube search: id, title, channel, length.
window.VIDEOS = {
  "neetcode big o notation": {"id": "BgLTDT03QtU", "title": "Big-O Notation - For Coding Interviews", "ch": "NeetCode", "len": "20:38"},
  "bytebytego what happens when you type a url": {"id": "AlkDbnbv7dk", "title": "What happens when you type a URL into your browser?", "ch": "ByteByteGo", "len": "5:20"},
  "bytebytego rest vs graphql vs grpc": {"id": "yWzKJPw_VzM", "title": "What Is GraphQL? REST vs. GraphQL", "ch": "ByteByteGo", "len": "5:15"},
  "websockets vs long polling vs server sent events": {"id": "3Ud6Ds2abO8", "title": "Long Polling vs SSE vs WebSockets vs QUIC | Simply Explained", "ch": "TechPrep", "len": "10:42"},
  "vertical vs horizontal scaling system design": {"id": "xpDnVSmNFX0", "title": "System Design BASICS: Horizontal vs. Vertical Scaling", "ch": "Gaurav Sen", "len": "7:56"},
  "bytebytego load balancer": {"id": "LQuuoHTyYz8", "title": "What is a LOAD BALANCER really about?", "ch": "ByteByteGo", "len": "6:45"},
  "neetcode two pointers": {"id": "MQmUVokbTrs", "title": "Coding Interview Patterns - Two Pointers", "ch": "Nikhil Lohia", "len": "19:02"},
  "system design back of the envelope estimation": {"id": "DwqTon7ZS_s", "title": "Back of Envelope Calculation - System Design Concept", "ch": "Piyush Garg", "len": "16:40"},
  "bytebytego caching strategies": {"id": "dGAgxozNWFE", "title": "Cache Systems Every Developer Should Know", "ch": "ByteByteGo", "len": "5:48"},
  "neetcode sliding window": {"id": "y2d0VHdvfdc", "title": "Sliding Window in 7 minutes | LeetCode Pattern", "ch": "AlgoMasterIO", "len": "7:38"},
  "bytebytego cdn": {"id": "RI9np1LWzqw", "title": "What Is A CDN? How Does It Work?", "ch": "ByteByteGo", "len": "4:24"},
  "bytebytego object block file storage": {"id": "sswLpKeAoxs", "title": "Block vs Object vs File Storage | Cloud Storage Types Explained", "ch": "Learn with Whiteboard", "len": "7:31"},
  "bytebytego sql vs nosql": {"id": "kkeFE6iRfMM", "title": "How To Choose The Right Database?", "ch": "ByteByteGo", "len": "6:58"},
  "neetcode stack": {"id": "mcOXqqX6D54", "title": "Coding Interview Patterns - Stacks | Monotonic Stacks | 8 different problems in a single video", "ch": "Nikhil Lohia", "len": "32:42"},
  "bytebytego database replication": {"id": "bI8Ry6GhMSE", "title": "Database Replication Explained (in 5 Minutes)", "ch": "Aced (formerly Exponent)", "len": "5:02"},
  "bytebytego database sharding": {"id": "_1IKwnbscQU", "title": "7 Must-know Strategies to Scale Your Database", "ch": "ByteByteGo", "len": "8:42"},
  "bytebytego consistent hashing": {"id": "UF9Iqmg94tk", "title": "Consistent Hashing | Algorithms You Should Know #1", "ch": "ByteByteGo", "len": "8:04"},
  "neetcode binary search": {"id": "y6SG0rE6nn4", "title": "Coding Interview Patterns - Binary Search | 8 different problems in a single video", "ch": "Nikhil Lohia", "len": "26:06"},
  "bytebytego cap theorem": {"id": "BHqjEjzAicA", "title": "CAP Theorem Simplified", "ch": "ByteByteGo", "len": "5:33"},
  "bytebytego kafka vs rabbitmq": {"id": "x4k1XEjNzYQ", "title": "Kafka vs. RabbitMQ vs. Messaging Middleware vs. Pulsar", "ch": "ByteByteGo", "len": "4:31"},
  "neetcode linked list": {"id": "Evm1grTr8J4", "title": "Lec-75: Linked List in Python 🐍 with Easiest Explanation & Execution", "ch": "Gate Smashers", "len": "12:35"},
  "bytebytego monolith vs microservices": {"id": "lTAcCNbJ7KE", "title": "What Are Microservices Really All About? (And When Not To Use It)", "ch": "ByteByteGo", "len": "4:45"},
  "bytebytego api gateway": {"id": "6ULyxuHKxg8", "title": "What is API Gateway?", "ch": "ByteByteGo", "len": "3:26"},
  "bytebytego rate limiting algorithms": {"id": "YXkOdWBwqaA", "title": "Rate Limiter System Design: Token Bucket, Leaky Bucket, Scaling", "ch": "ByteByteGo", "len": "7:46"},
  "circuit breaker retry exponential backoff system design": {"id": "HRS9mIfiNn4", "title": "Introduction to circuit breaker in microservices (for beginners)", "ch": "sudoCODE", "len": "11:37"},
  "neetcode binary tree traversal": {"id": "9RHO6jU--GU", "title": "Binary tree traversal - breadth-first and depth-first strategies", "ch": "mycodeschool", "len": "11:54"},
  "database normalization 1nf 2nf 3nf explained": {"id": "GFQaEYEc8_8", "title": "Learn Database Normalization - 1NF, 2NF, 3NF, 4NF, 5NF", "ch": "Decomplexify", "len": "28:34"},
  "bytebytego design url shortener": {"id": "HHUi8F_qAXM", "title": "How Does a URL Shortener Work?", "ch": "ByteByteGo", "len": "6:44"},
  "bytebytego design rate limiter": {"id": "YXkOdWBwqaA", "title": "Rate Limiter System Design: Token Bucket, Leaky Bucket, Scaling", "ch": "ByteByteGo", "len": "7:46"},
  "bytebytego design notification system": {"id": "bBTPZ9NdSk8", "title": "System Design Interview - Notification Service", "ch": "System Design Interview", "len": "25:11"},
  "neetcode heap priority queue": {"id": "E2v9hBgG6gE", "title": "Heaps & Priority Queues - Heapify, Heap Sort, Heapq Library - DSA Course in Python Lecture 9", "ch": "Greg Hogg", "len": "24:08"},
  "bytebytego design chat system": {"id": "okrR1KXNLtA", "title": "FAANG System Design Interview: Design A Chat System (WhatsApp, Facebook Messenger, Discord, Slack)", "ch": "ByteByteGo", "len": "8:45"},
  "bytebytego design news feed system": {"id": "Qj4-GruzyDU", "title": "Design FB News Feed System Design Interview w/ ex: Meta Senior Manager", "ch": "Hello Interview", "len": "26:12"},
  "neetcode number of islands graph": {"id": "pV2kpPD66nE", "title": "NUMBER OF ISLANDS - Leetcode 200 - Python", "ch": "NeetCode", "len": "11:41"},
  "system design ecommerce order checkout": {"id": "2811UT5r5Jk", "title": "E-Commerce Platform (Amazon, eBay): System Design Interview (Stripe & Amazon Offers)", "ch": "TechPrep", "len": "12:10"},
  "bytebytego unique id generator snowflake": {"id": "SnyFRsPtoy4", "title": "Generating Unique IDs at Scale: Inside Twitter’s Snowflake System Design", "ch": "Ultimate System Design", "len": "8:48"},
  "neetcode backtracking subsets": {"id": "REOH22Xwdkk", "title": "Subsets - Backtracking - Leetcode 78", "ch": "NeetCode", "len": "8:47"},
  "bytebytego design google drive dropbox": {"id": "_UZ1ngy-kOI", "title": "Design Dropbox or Google Drive w/ a Ex-Meta Staff Engineer System Design Interview", "ch": "Hello Interview", "len": "58:08"},
  "neetcode dynamic programming climbing stairs": {"id": "sWnBVPRA0yQ", "title": "5 steps to solve any Dynamic Programming problem", "ch": "Sahil & Sarra", "len": "8:43"},
  "system design ticket booking ticketmaster": {"id": "fhdPyoO6aXI", "title": "System Design Interview: Design Ticketmaster w/ a Ex-Meta Staff Engineer", "ch": "Hello Interview", "len": "58:39"},
  "neetcode Two Sum": {"id": "KLlXCFG5TnA", "title": "Two Sum - Leetcode 1 - HashMap - Python", "ch": "NeetCode", "len": "8:26"},
  "neetcode Contains Duplicate": {"id": "3OamzN90kPg", "title": "Contains Duplicate - Leetcode 217 - Python", "ch": "NeetCode", "len": "6:31"},
  "neetcode Valid Anagram": {"id": "9UtInBqnCgA", "title": "Valid Anagram - Leetcode 242 - Python", "ch": "NeetCode", "len": "12:01"},
  "neetcode Group Anagrams": {"id": "vzdNOK2oB2E", "title": "Group Anagrams - Categorize Strings by Count - Leetcode 49", "ch": "NeetCode", "len": "8:12"},
  "neetcode Top K Frequent Elements": {"id": "YPTqKIgVk-k", "title": "Top K Frequent Elements - Bucket Sort - Leetcode 347 - Python", "ch": "NeetCode", "len": "13:13"},
  "neetcode Ransom Note": {"id": "i3bvxJyUB40", "title": "Ransom Note - Leetcode 383 - Hashmaps & Sets (Python)", "ch": "Greg Hogg", "len": "8:34"},
  "neetcode Product of Array Except Self": {"id": "bNvIQI2wAjk", "title": "Product of Array Except Self - Leetcode 238 - Python", "ch": "NeetCode", "len": "11:54"},
  "neetcode Valid Sudoku": {"id": "TjFXEUCMqI8", "title": "Valid Sudoku - Amazon Interview Question - Leetcode 36 - Python", "ch": "NeetCode", "len": "13:28"},
  "neetcode Longest Consecutive Sequence": {"id": "P6RZZMu_maU", "title": "Leetcode 128 - LONGEST CONSECUTIVE SEQUENCE", "ch": "NeetCode", "len": "9:24"},
  "neetcode Valid Palindrome": {"id": "jJXJ16kPFWg", "title": "Valid Palindrome - Leetcode 125 - Python", "ch": "NeetCode", "len": "14:58"},
  "neetcode Two Sum II - Input Array Is Sorted": {"id": "cQ1Oz4ckceM", "title": "TWO SUM II - Amazon Coding Interview Question - Leetcode 167 - Python", "ch": "NeetCode", "len": "8:18"},
  "neetcode 3Sum": {"id": "jzZsG8n2R9A", "title": "3Sum - Leetcode 15 - Python", "ch": "NeetCode", "len": "12:54"},
  "neetcode Container With Most Water": {"id": "UuiTKBwPgAo", "title": "Container with Most Water - Leetcode 11 - Python", "ch": "NeetCode", "len": "12:37"},
  "neetcode Move Zeroes": {"id": "aayNRwUN3Do", "title": "Move Zeroes - Leetcode 283 - Python", "ch": "NeetCode", "len": "8:15"},
  "neetcode Remove Duplicates from Sorted Array": {"id": "DEJAZBq0FDA", "title": "Remove Duplicates from Sorted Array - Leetcode 26 - Python", "ch": "NeetCode", "len": "10:38"},
  "neetcode Best Time to Buy and Sell Stock": {"id": "1pkOgXD63yU", "title": "Sliding Window: Best Time to Buy and Sell Stock - Leetcode 121 - Python", "ch": "NeetCode", "len": "8:46"},
  "neetcode Longest Substring Without Repeating Characters": {"id": "wiGpQwVHdE0", "title": "Longest Substring Without Repeating Characters - Leetcode 3 - Python", "ch": "NeetCode", "len": "6:46"},
  "neetcode Longest Repeating Character Replacement": {"id": "gqXU1UyA8pk", "title": "Longest Repeating Character Replacement - Leetcode 424 - Python", "ch": "NeetCode", "len": "20:44"},
  "neetcode Permutation in String": {"id": "UbyhOgBN834", "title": "Permutation in String - Leetcode 567 - Python", "ch": "NeetCode", "len": "19:40"},
  "neetcode Range Sum Query - Immutable": {"id": "2pndAmo_sMA", "title": "Range Sum Query Immutable - Leetcode 303 - Python", "ch": "NeetCodeIO", "len": "7:42"},
  "neetcode Subarray Sum Equals K": {"id": "fFVZt-6sgyo", "title": "Subarray Sum Equals K - Prefix Sums - Leetcode 560 - Python", "ch": "NeetCode", "len": "15:19"},
  "neetcode Valid Parentheses": {"id": "WTzjTskDFMg", "title": "Valid Parentheses - Stack - Leetcode 20 - Python", "ch": "NeetCode", "len": "10:43"},
  "neetcode Min Stack": {"id": "qkLl7nAwDPo", "title": "Design Min Stack - Amazon Interview Question - Leetcode 155 - Python", "ch": "NeetCode", "len": "8:53"},
  "neetcode Evaluate Reverse Polish Notation": {"id": "iu0082c4HDE", "title": "Evaluate Reverse Polish Notation - Leetcode 150 - Python", "ch": "NeetCode", "len": "9:20"},
  "neetcode Daily Temperatures": {"id": "cTBiBSnjO3c", "title": "Daily Temperatures - Monotonic Stack - Leetcode 739 - Python", "ch": "NeetCode", "len": "11:52"},
  "neetcode Next Greater Element I": {"id": "68a1Dc_qVq4", "title": "Next Greater Element I - Leetcode 496 - Python", "ch": "NeetCode", "len": "14:53"},
  "neetcode Implement Queue using Stacks": {"id": "eanwa3ht3YQ", "title": "Implement Queue using Stacks - Leetcode 232 - Python", "ch": "NeetCodeIO", "len": "15:23"},
  "neetcode Binary Search": {"id": "s4DPM8ct1pI", "title": "Binary Search - Leetcode 704 - Python", "ch": "NeetCode", "len": "9:40"},
  "neetcode Search Insert Position": {"id": "K-RYzDZkzCI", "title": "Search Insert Position - Binary Search - Leetcode 35 - Python", "ch": "NeetCode", "len": "13:42"},
  "neetcode Search a 2D Matrix": {"id": "Ber2pi2C0j0", "title": "Search a 2D Matrix - Leetcode 74 - Python", "ch": "NeetCode", "len": "10:59"},
  "neetcode Koko Eating Bananas": {"id": "U2SozAs9RzA", "title": "Koko Eating Bananas - Binary Search - Leetcode 875 - Python", "ch": "NeetCode", "len": "15:12"},
  "neetcode Find Minimum in Rotated Sorted Array": {"id": "nIVW4P8b1VA", "title": "Find Minimum in Rotated Sorted Array - Binary Search - Leetcode 153 - Python", "ch": "NeetCode", "len": "12:30"},
  "neetcode Search in Rotated Sorted Array": {"id": "U8XENwh8Oy8", "title": "Search in rotated sorted array - Leetcode 33 - Python", "ch": "NeetCode", "len": "13:28"},
  "neetcode Reverse Linked List": {"id": "G0_I-ZF0S38", "title": "Reverse Linked List - Iterative AND Recursive - Leetcode 206 - Python", "ch": "NeetCode", "len": "11:07"},
  "neetcode Merge Two Sorted Lists": {"id": "XIdigk956u0", "title": "Merge Two Sorted Lists - Leetcode 21 - Python", "ch": "NeetCode", "len": "6:16"},
  "neetcode Linked List Cycle": {"id": "gBTe7lFR3vc", "title": "Linked List Cycle - Floyd's Tortoise and Hare - Leetcode 141 - Python", "ch": "NeetCode", "len": "10:44"},
  "neetcode Middle of the Linked List": {"id": "A2_ldqM4QcY", "title": "Middle of the Linked List - Leetcode 876 - Python", "ch": "NeetCodeIO", "len": "4:57"},
  "neetcode Remove Nth Node From End of List": {"id": "XVuQxVej6y8", "title": "Remove Nth Node from End of List - Oracle Interview Question - Leetcode 19", "ch": "NeetCode", "len": "7:09"},
  "neetcode Reorder List": {"id": "S5bfdUTrKLM", "title": "Linkedin Interview Question - Reorder List - Leetcode 143 - Python", "ch": "NeetCode", "len": "13:47"},
  "neetcode LRU Cache": {"id": "7ABFKPK2hD4", "title": "LRU Cache - Twitch Interview Question - Leetcode 146", "ch": "NeetCode", "len": "17:49"},
  "neetcode Add Two Numbers": {"id": "wgFPrzTjm7s", "title": "Add Two Numbers - Leetcode 2 - Python", "ch": "NeetCode", "len": "9:33"},
  "neetcode Maximum Depth of Binary Tree": {"id": "hTM3phVI6YQ", "title": "Maximum Depth of Binary Tree - 3 Solutions - Leetcode 104 - Python", "ch": "NeetCode", "len": "16:43"},
  "neetcode Invert Binary Tree": {"id": "OnSn2XEQ4MY", "title": "Invert Binary Tree - Depth First Search - Leetcode 226", "ch": "NeetCode", "len": "3:55"},
  "neetcode Same Tree": {"id": "vRbbcKXCxOw", "title": "Same Tree - Leetcode 100 - Python", "ch": "NeetCode", "len": "7:52"},
  "neetcode Subtree of Another Tree": {"id": "E36O5SWp-LE", "title": "Subtree of Another Tree - Leetcode 572 - Python", "ch": "NeetCode", "len": "14:15"},
  "neetcode Diameter of Binary Tree": {"id": "K81C31ytOZE", "title": "Diameter of Binary Tree - Leetcode 543 - Python", "ch": "NeetCodeIO", "len": "7:26"},
  "neetcode Balanced Binary Tree": {"id": "QfJsau0ItOY", "title": "Balanced Binary Tree - Leetcode 110 - Python", "ch": "NeetCode", "len": "13:11"},
  "neetcode Binary Tree Level Order Traversal": {"id": "6ZnyEApgFYg", "title": "Binary Tree Level Order Traversal - BFS - Leetcode 102", "ch": "NeetCode", "len": "9:36"},
  "neetcode Binary Tree Right Side View": {"id": "d4zLyf32e3I", "title": "Binary Tree Right Side View - Breadth First Search - Leetcode 199", "ch": "NeetCode", "len": "10:16"},
  "neetcode Lowest Common Ancestor of a Binary Search Tree": {"id": "gs2LMfuOR9k", "title": "Lowest Common Ancestor of a Binary Search Tree - Leetcode 235 - Python", "ch": "NeetCode", "len": "6:43"},
  "neetcode Validate Binary Search Tree": {"id": "s6ATEkipzow", "title": "Validate Binary Search Tree - Depth First Search - Leetcode 98", "ch": "NeetCode", "len": "9:56"},
  "neetcode Kth Smallest Element in a BST": {"id": "5LUXSvjmGCw", "title": "Kth Smallest Element in a BST - Leetcode 230 - Python", "ch": "NeetCode", "len": "10:56"},
  "neetcode Count Good Nodes in Binary Tree": {"id": "7cp5imvDzl4", "title": "Microsoft's Most Asked Question 2021 - Count Good Nodes in a Binary Tree - Leetcode 1448 - Python", "ch": "NeetCode", "len": "8:18"},
  "neetcode Kth Largest Element in a Stream": {"id": "hOjcdrqMoQ8", "title": "Kth Largest Element in a Stream - Leetcode 703 - Python", "ch": "NeetCode", "len": "11:18"},
  "neetcode Last Stone Weight": {"id": "B-QCq79-Vfw", "title": "Last Stone Weight - Priority Queue - Leetcode 1046 - Python", "ch": "NeetCode", "len": "12:38"},
  "neetcode Kth Largest Element in an Array": {"id": "XEmy13g1Qxc", "title": "Kth Largest Element in an Array - Quick Select - Leetcode 215 - Python", "ch": "NeetCode", "len": "18:48"},
  "neetcode K Closest Points to Origin": {"id": "rI2EBUEMfTk", "title": "K Closest Points to Origin - Heap / Priority Queue - Leetcode 973 - Python", "ch": "NeetCode", "len": "9:29"},
  "neetcode Task Scheduler": {"id": "s8p8ukTyA2I", "title": "Task Scheduler - Leetcode 621 - Python", "ch": "NeetCode", "len": "17:07"},
  "neetcode Number of Islands": {"id": "pV2kpPD66nE", "title": "NUMBER OF ISLANDS - Leetcode 200 - Python", "ch": "NeetCode", "len": "11:41"},
  "neetcode Flood Fill": {"id": "hEZ8uGqaC2c", "title": "Leetcode 733. Flood Fill - Python", "ch": "HelmyCodeCamp", "len": "6:56"},
  "neetcode Max Area of Island": {"id": "iJGr1OtmH0c", "title": "Max Area of Island - Leetcode 695 - Python", "ch": "NeetCode", "len": "11:14"},
  "neetcode Clone Graph": {"id": "mQeF6bN8hMk", "title": "Clone Graph - Depth First Search - Leetcode 133", "ch": "NeetCode", "len": "11:48"},
  "neetcode Rotting Oranges": {"id": "y704fEOx0s0", "title": "Rotting Oranges - Leetcode 994 - Python", "ch": "NeetCode", "len": "12:19"},
  "neetcode Course Schedule": {"id": "EgI5nU9etnU", "title": "Course Schedule - Graph Adjacency List - Leetcode 207", "ch": "NeetCode", "len": "15:47"},
  "neetcode Subsets": {"id": "REOH22Xwdkk", "title": "Subsets - Backtracking - Leetcode 78", "ch": "NeetCode", "len": "8:47"},
  "neetcode Permutations": {"id": "FZe0UqISmUw", "title": "Permutations - Leetcode 46 - Python", "ch": "NeetCodeIO", "len": "11:58"},
  "neetcode Combination Sum": {"id": "GBKI9VSKdGg", "title": "Combination Sum - Backtracking - Leetcode 39 - Python", "ch": "NeetCode", "len": "15:10"},
  "neetcode Climbing Stairs": {"id": "Y0lT9Fck7qI", "title": "Climbing Stairs - Dynamic Programming - Leetcode 70 - Python", "ch": "NeetCode", "len": "18:08"},
  "neetcode Min Cost Climbing Stairs": {"id": "ktmzAZWkEZ0", "title": "Min Cost Climbing Stairs - Dynamic Programming - Leetcode 746 - Python", "ch": "NeetCode", "len": "19:27"},
  "neetcode House Robber": {"id": "73r3KWiEvyk", "title": "House Robber -  Leetcode 198 - Python Dynamic Programming", "ch": "NeetCode", "len": "10:35"},
  "neetcode Coin Change": {"id": "H9bfqozjoqs", "title": "Coin Change - Dynamic Programming Bottom Up - Leetcode 322", "ch": "NeetCode", "len": "19:23"},
  "neetcode Maximum Subarray": {"id": "5WZl3MMT0Eg", "title": "Maximum Subarray - Amazon Coding Interview Question - Leetcode 53 - Python", "ch": "NeetCode", "len": "8:03"},
  "neetcode Unique Paths": {"id": "IlEsdxuD4lY", "title": "Unique Paths - Dynamic Programming - Leetcode 62", "ch": "NeetCode", "len": "10:48"},
  "neetcode Merge Intervals": {"id": "44H3cEC2fFM", "title": "Merge Intervals - Sorting - Leetcode 56", "ch": "NeetCode", "len": "10:15"},
  "neetcode Insert Interval": {"id": "A8NUOmlwOlM", "title": "Insert Interval - Leetcode 57 - Python", "ch": "NeetCode", "len": "11:51"},
};
